---
- name: Install software for ryoung
  hosts: all
  connection: local
  remote_user: ryoung

  vars:
    homebrew_path: /opt/homebrew
    ruby_path: "{{ homebrew_path }}/opt/ruby@3.3"

  tasks:
  - name: Install software
    become: no
    homebrew:
      name: 
      - nvim
      - tmux
      - python3
      - openvpn
      - nmap
      - htop
      - ripgrep
      - wget
      - unzip
      - gopls
      - pipx
      - ruby@3.3
      - terraform-ls
      state: installed
      update_homebrew: yes

  - name: Install pylsp
    shell: pipx install python-lsp-server

  - name: Install ruby-lsp
    gem:
      name: ruby-lsp
      state: present

  - name: Ruby links
    block:
      - name: ruby
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/ruby"
          dest: "{{ homebrew_path }}/bin/ruby"
          mode: "0775"
          owner: ryoung
          group: admin

      - name: rdoc
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/rdoc"
          dest: "{{ homebrew_path }}/bin/rdoc"
          mode: "0775"
          owner: ryoung
          group: admin

      - name: rake
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/rake"
          dest: "{{ homebrew_path }}/bin/rake"
          mode: "0775"
          owner: ryoung
          group: admin

      - name: rdbg
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/rdbg"
          dest: "{{ homebrew_path }}/bin/rdbg"
          mode: "0775"
          owner: ryoung
          group: admin

      - name: gem
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/gem"
          dest: "{{ homebrew_path }}/bin/gem"
          mode: "0775"
          owner: ryoung
          group: admin

      - name: erb
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/erb"
          dest: "{{ homebrew_path }}/bin/erb"
          mode: "0775"
          owner: ryoung
          group: admin

      - name: irb
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/irb"
          dest: "{{ homebrew_path }}/bin/irb"
          mode: "0775"
          owner: ryoung
          group: admin

      - name: ri
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/ri"
          dest: "{{ homebrew_path }}/bin/ri"
          mode: "0775"
          owner: ryoung
          group: admin

      - name: rbs
        ansible.builtin.file:
          state: link
          src: "{{ ruby_path }}/bin/rbs"
          dest: "{{ homebrew_path }}/bin/rbs"
          mode: "0775"
          owner: ryoung
          group: admin

    #- name: Installing docker cask
      #become: no
      #homebrew:
        #name: homebrew/cask/1password
        #state: present
      #ignore_errors: yes

    #- name: Installing 1password cask
      #become: no
      #homebrew:
        #name: homebrew/cask/docker
        #state: present
      #ignore_errors: yes

    #- name: Installing 1password-cli cask
      #become: no
      #homebrew:
      #name: homebrew/cask/1password-cli
      #state: present
      #ignore_errors: yes

  - name: Remove software
    become: no
    homebrew:
      name:
      - apache2
      state: absent

  - name: Install zshrc into home
    copy:
      src: mac_zshrc
      dest: "{{ ansible_env.HOME }}/.zshrc"
      owner: ryoung
      group: staff
      mode: '0644'
      force: true

  - name: Create git folder
    file:
      path: "{{ ansible_facts['env']['HOME'] }}/git"
      state: directory
      mode: 0755

  - name: Create .config folder
    file:
      path: "{{ ansible_facts['env']['HOME'] }}/.config"
      state: directory
      mode: 0755

  - name: Create link for neovim config
    file:
      path: "{{ ansible_facts['env']['HOME'] }}/.config/nvim"
      src: "{{ ansible_facts['env']['HOME'] }}/git/dotfiles/nvim"
      state: link
      mode: 0755

  - name: Create link for tmux config
    file:
      path: "{{ ansible_facts['env']['HOME'] }}/.tmux.conf"
      src: "{{ ansible_facts['env']['HOME'] }}/git/dotfiles/tmux/tmux.conf.symlink"
      state: link
      mode: 0755

