---
- name: Install software for ryoung
  hosts: all
  connection: local
  remote_user: ryoung

  tasks:
  #- name: Set package names for system

  - name: Install software
    become: no
    homebrew:
      name: 
      - nvim
      - tmux
      - python3
      - openvpn
      - nmap
      - htop
      - ripgrep
      - wget
      - unzip
      - gopls
      - pylsp
      state: installed
      update_homebrew: yes

    #- name: Installing docker cask
      #become: no
      #homebrew:
        #name: homebrew/cask/1password
        #state: present
      #ignore_errors: yes

    #- name: Installing 1password cask
      #become: no
      #homebrew:
        #name: homebrew/cask/docker
        #state: present
      #ignore_errors: yes

    #- name: Installing 1password-cli cask
      #become: no
      #homebrew:
      #name: homebrew/cask/1password-cli
      #state: present
      #ignore_errors: yes

  - name: Remove software
    become: no
    homebrew:
      name:
      - apache2
      state: absent

  - name: Install zshrc into home
    copy:
      src: mac_zshrc
      dest: "{{ ansible_env.HOME }}/.zshrc"
      owner: ryoung
      group: staff
      mode: '0644'
      force: true

  - name: Create git folder
    file:
      path: "{{ ansible_facts['env']['HOME'] }}/git"
      state: directory
      mode: 0755

  - name: Git clone dotfiles
    git:
      repo: "https://github.com/ryoung9550/dotfiles.git"
      dest: "{{ ansible_facts['env']['HOME'] }}/git/dotfiles"

  - name: Create .config folder
    file:
      path: "{{ ansible_facts['env']['HOME'] }}/.config"
      state: directory
      mode: 0755

  - name: Create link for neovim config
    file:
      path: "{{ ansible_facts['env']['HOME'] }}/.config/nvim"
      src: "{{ ansible_facts['env']['HOME'] }}/git/dotfiles/nvim"
      state: link
      mode: 0755

  - name: Create link for tmux config
    file:
      path: "{{ ansible_facts['env']['HOME'] }}/.tmux.conf"
      src: "{{ ansible_facts['env']['HOME'] }}/git/dotfiles/tmux/tmux.conf.symlink"
      state: link
      mode: 0755

